const sampleMedicines = [
  {
    name: "Paracetamol 500mg",
    genericName: "Paracetamol",
    groupName: "Analgesics",
    manufacturer: "ABC Pharma",
    unitPrice: 0.5,
    stripPrice: 5.0,
    unitsPerStrip: 10,
    stockQuantity: 500,
    dosage: "1-2 tablets every 4-6 hours as needed",
    instructions: "Take with or without food. Do not exceed 8 tablets in 24 hours.",
    precautions: "Avoid alcohol. Not recommended for long-term use without medical supervision.",
    sideEffects: "Rare side effects include nausea, stomach pain, and allergic reactions.",
  },
  {
    name: "Amoxicillin 250mg",
    genericName: "Amoxicillin",
    groupName: "Antibiotics",
    manufacturer: "XYZ Pharmaceuticals",
    unitPrice: 1.2,
    stripPrice: 12.0,
    unitsPerStrip: 10,
    stockQuantity: 300,
    dosage: "1 capsule three times daily",
    instructions: "Take with food. Complete the full course even if you feel better.",
    precautions: "Inform your doctor if you have allergies to penicillin or other antibiotics.",
    sideEffects: "Diarrhea, nausea, vomiting, rash.",
  },
  {
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    groupName: "Proton Pump Inhibitors",
    manufacturer: "MediCorp",
    unitPrice: 0.8,
    stripPrice: 8.0,
    unitsPerStrip: 10,
    stockQuantity: 250,
    dosage: "1 capsule daily before breakfast",
    instructions: "Swallow whole with water. Do not crush or chew.",
    precautions: "Long-term use may increase risk of bone fractures.",
    sideEffects: "Headache, abdominal pain, diarrhea, nausea.",
  },
  {
    name: "Atorvastatin 10mg",
    genericName: "Atorvastatin",
    groupName: "Statins",
    manufacturer: "HealthPharm",
    unitPrice: 1.5,
    stripPrice: 15.0,
    unitsPerStrip: 10,
    stockQuantity: 200,
    dosage: "1 tablet daily, preferably in the evening",
    instructions: "Take with or without food. Avoid grapefruit juice.",
    precautions: "Report muscle pain or weakness to your doctor immediately.",
    sideEffects: "Muscle pain, liver problems, digestive issues.",
  },
  {
    name: "Metformin 500mg",
    genericName: "Metformin",
    groupName: "Antidiabetics",
    manufacturer: "DiabeCare",
    unitPrice: 0.6,
    stripPrice: 6.0,
    unitsPerStrip: 10,
    stockQuantity: 350,
    dosage: "1 tablet twice daily with meals",
    instructions: "Take with food to reduce stomach upset.",
    precautions: "Avoid alcohol. May cause vitamin B12 deficiency with long-term use.",
    sideEffects: "Nausea, diarrhea, stomach upset, metallic taste.",
  },
  {
    name: "Losartan 50mg",
    genericName: "Losartan",
    groupName: "Angiotensin II Receptor Blockers",
    manufacturer: "CardioHealth",
    unitPrice: 1.0,
    stripPrice: 10.0,
    unitsPerStrip: 10,
    stockQuantity: 180,
    dosage: "1 tablet daily",
    instructions: "Can be taken with or without food at the same time each day.",
    precautions: "May cause dizziness. Avoid potassium supplements without consulting doctor.",
    sideEffects: "Dizziness, cough, diarrhea, fatigue.",
  },
  {
    name: "Cetirizine 10mg",
    genericName: "Cetirizine",
    groupName: "Antihistamines",
    manufacturer: "AllergyRelief",
    unitPrice: 0.7,
    stripPrice: 7.0,
    unitsPerStrip: 10,
    stockQuantity: 400,
    dosage: "1 tablet daily",
    instructions: "Take with or without food. May cause drowsiness.",
    precautions: "Avoid alcohol. Use caution when driving or operating machinery.",
    sideEffects: "Drowsiness, dry mouth, fatigue.",
  },
  {
    name: "Ibuprofen 400mg",
    genericName: "Ibuprofen",
    groupName: "NSAIDs",
    manufacturer: "PainAway",
    unitPrice: 0.6,
    stripPrice: 6.0,
    unitsPerStrip: 10,
    stockQuantity: 450,
    dosage: "1 tablet every 4-6 hours as needed",
    instructions: "Take with food or milk to reduce stomach upset.",
    precautions: "Not recommended for those with heart conditions or stomach ulcers.",
    sideEffects: "Stomach pain, heartburn, dizziness, rash.",
  },
  {
    name: "Amlodipine 5mg",
    genericName: "Amlodipine",
    groupName: "Calcium Channel Blockers",
    manufacturer: "BPControl",
    unitPrice: 0.9,
    stripPrice: 9.0,
    unitsPerStrip: 10,
    stockQuantity: 220,
    dosage: "1 tablet daily",
    instructions: "Can be taken with or without food at the same time each day.",
    precautions: "May cause swelling in ankles or feet.",
    sideEffects: "Swelling, dizziness, flushing, headache.",
  },
  {
    name: "Azithromycin 250mg",
    genericName: "Azithromycin",
    groupName: "Macrolide Antibiotics",
    manufacturer: "InfectionCure",
    unitPrice: 2.0,
    stripPrice: 20.0,
    unitsPerStrip: 10,
    stockQuantity: 150,
    dosage: "Varies by condition, typically 1 tablet daily for 3-5 days",
    instructions: "Take at least 1 hour before or 2 hours after meals.",
    precautions: "Inform your doctor if you have heart rhythm problems.",
    sideEffects: "Diarrhea, nausea, abdominal pain.",
  },
  {
    name: "Salbutamol 4mg",
    genericName: "Salbutamol",
    groupName: "Bronchodilators",
    manufacturer: "RespiraCare",
    unitPrice: 0.4,
    stripPrice: 4.0,
    unitsPerStrip: 10,
    stockQuantity: 600,
    dosage: "1 tablet every 4-6 hours as needed",
    instructions: "Take with or without food. Shake well if using inhaler form.",
    precautions: "May cause increased heart rate. Inform doctor if you have heart conditions.",
    sideEffects: "Tremors, headache, palpitations.",
  },
  {
    name: "Fluoxetine 20mg",
    genericName: "Fluoxetine",
    groupName: "SSRIs",
    manufacturer: "MindHealth",
    unitPrice: 1.3,
    stripPrice: 13.0,
    unitsPerStrip: 10,
    stockQuantity: 200,
    dosage: "1 capsule daily in the morning",
    instructions: "Can be taken with or without food. Do not stop abruptly.",
    precautions: "May increase suicidal thoughts in young adults. Consult doctor before use.",
    sideEffects: "Insomnia, nausea, headache, fatigue.",
  },
  {
    name: "Hydrochlorothiazide 25mg",
    genericName: "Hydrochlorothiazide",
    groupName: "Diuretics",
    manufacturer: "AquaPharm",
    unitPrice: 0.5,
    stripPrice: 5.0,
    unitsPerStrip: 10,
    stockQuantity: 300,
    dosage: "1 tablet daily in the morning",
    instructions: "Take with or without food. Stay hydrated.",
    precautions: "Monitor electrolyte levels. Avoid in severe kidney disease.",
    sideEffects: "Dizziness, dehydration, low potassium levels.",
  },
  {
    name: "Levothyroxine 50mcg",
    genericName: "Levothyroxine",
    groupName: "Thyroid Hormones",
    manufacturer: "ThyroCare",
    unitPrice: 0.8,
    stripPrice: 8.0,
    unitsPerStrip: 10,
    stockQuantity: 250,
    dosage: "1 tablet daily on an empty stomach",
    instructions: "Take 30-60 minutes before breakfast. Avoid calcium or iron supplements within 4 hours.",
    precautions: "Monitor heart rate and thyroid function regularly.",
    sideEffects: "Weight loss, palpitations, sweating, nervousness.",
  },
  {
    name: "Montelukast 10mg",
    genericName: "Montelukast",
    groupName: "Leukotriene Inhibitors",
    manufacturer: "AllergyEase",
    unitPrice: 1.1,
    stripPrice: 11.0,
    unitsPerStrip: 10,
    stockQuantity: 280,
    dosage: "1 tablet daily in the evening",
    instructions: "Take with or without food. Not for acute asthma attacks.",
    precautions: "May cause mood changes. Report behavioral changes to doctor.",
    sideEffects: "Headache, abdominal pain, fatigue.",
  },
  {
    name: "Prednisolone 5mg",
    genericName: "Prednisolone",
    groupName: "Corticosteroids",
    manufacturer: "InflameAway",
    unitPrice: 0.7,
    stripPrice: 7.0,
    unitsPerStrip: 10,
    stockQuantity: 320,
    dosage: "Varies, typically 1-4 tablets daily",
    instructions: "Take with food to reduce stomach upset. Follow tapering schedule if long-term use.",
    precautions: "Long-term use may cause bone loss or increased infection risk.",
    sideEffects: "Weight gain, insomnia, mood changes, increased appetite.",
  },
  {
    name: "Clopidogrel 75mg",
    genericName: "Clopidogrel",
    groupName: "Antiplatelets",
    manufacturer: "HeartGuard",
    unitPrice: 1.4,
    stripPrice: 14.0,
    unitsPerStrip: 10,
    stockQuantity: 190,
    dosage: "1 tablet daily",
    instructions: "Can be taken with or without food.",
    precautions: "Increased risk of bleeding. Inform doctor before surgery.",
    sideEffects: "Bleeding, bruising, diarrhea, stomach pain.",
  },
  {
    name: "Sertraline 50mg",
    genericName: "Sertraline",
    groupName: "SSRIs",
    manufacturer: "MindBalance",
    unitPrice: 1.2,
    stripPrice: 12.0,
    unitsPerStrip: 10,
    stockQuantity: 210,
    dosage: "1 tablet daily in the morning or evening",
    instructions: "Take with or without food. Consistent timing improves efficacy.",
    precautions: "Avoid abrupt discontinuation. Monitor for suicidal thoughts initially.",
    sideEffects: "Nausea, insomnia, headache, sexual dysfunction.",
  },
  {
    name: "Ranitidine 150mg",
    genericName: "Ranitidine",
    groupName: "H2 Receptor Blockers",
    manufacturer: "GutRelief",
    unitPrice: 0.6,
    stripPrice: 6.0,
    unitsPerStrip: 10,
    stockQuantity: 400,
    dosage: "1 tablet twice daily",
    instructions: "Take with or without food. Avoid smoking to improve efficacy.",
    precautions: "Consult doctor if symptoms persist beyond 2 weeks.",
    sideEffects: "Headache, constipation, diarrhea, dizziness.",
  },
  {
    name: "Doxycycline 100mg",
    genericName: "Doxycycline",
    groupName: "Tetracycline Antibiotics",
    manufacturer: "BactiCure",
    unitPrice: 1.6,
    stripPrice: 16.0,
    unitsPerStrip: 10,
    stockQuantity: 170,
    dosage: "1 capsule twice daily for 7-14 days",
    instructions: "Take with a full glass of water. Avoid lying down for 30 minutes after dose.",
    precautions: "Avoid sun exposure. Not recommended for children under 8 or pregnant women.",
    sideEffects: "Nausea, photosensitivity, diarrhea, stomach upset.",
  },
  {
    name: "Lisinopril 10mg",
    genericName: "Lisinopril",
    groupName: "ACE Inhibitors",
    manufacturer: "CardioCare",
    unitPrice: 0.9,
    stripPrice: 9.0,
    unitsPerStrip: 10,
    stockQuantity: 260,
    dosage: "1 tablet daily",
    instructions: "Take with or without food. Consistent timing recommended.",
    precautions: "Monitor blood pressure and kidney function. Avoid in pregnancy.",
    sideEffects: "Cough, dizziness, headache, fatigue.",
  },
  {
    name: "Citalopram 20mg",
    genericName: "Citalopram",
    groupName: "SSRIs",
    manufacturer: "MoodLift",
    unitPrice: 1.1,
    stripPrice: 11.0,
    unitsPerStrip: 10,
    stockQuantity: 230,
    dosage: "1 tablet daily in the morning",
    instructions: "Take with or without food. Avoid abrupt discontinuation.",
    precautions: "May increase suicidal thoughts initially. Consult doctor before use.",
    sideEffects: "Nausea, dry mouth, sweating, insomnia.",
  },
  {
    name: "Simvastatin 20mg",
    genericName: "Simvastatin",
    groupName: "Statins",
    manufacturer: "CholestControl",
    unitPrice: 1.3,
    stripPrice: 13.0,
    unitsPerStrip: 10,
    stockQuantity: 210,
    dosage: "1 tablet daily in the evening",
    instructions: "Take with or without food. Avoid grapefruit juice.",
    precautions: "Monitor liver function. Report muscle pain immediately.",
    sideEffects: "Muscle pain, constipation, headache, nausea.",
  },
  {
    name: "Acyclovir 400mg",
    genericName: "Acyclovir",
    groupName: "Antivirals",
    manufacturer: "ViroCure",
    unitPrice: 1.8,
    stripPrice: 18.0,
    unitsPerStrip: 10,
    stockQuantity: 140,
    dosage: "1 tablet 2-5 times daily, depending on condition",
    instructions: "Take with or without food. Stay hydrated.",
    precautions: "Not recommended for patients with severe kidney disease.",
    sideEffects: "Nausea, diarrhea, headache, fatigue.",
  },
  {
    name: "Fluconazole 150mg",
    genericName: "Fluconazole",
    groupName: "Antifungals",
    manufacturer: "FungiClear",
    unitPrice: 2.5,
    stripPrice: 25.0,
    unitsPerStrip: 10,
    stockQuantity: 120,
    dosage: "1 tablet as a single dose or daily for 7-14 days",
    instructions: "Take with or without food. Follow prescribed duration.",
    precautions: "Monitor liver function with prolonged use.",
    sideEffects: "Nausea, headache, rash, abdominal pain.",
  },
  {
    name: "Gabapentin 300mg",
    genericName: "Gabapentin",
    groupName: "Anticonvulsants",
    manufacturer: "NeuroCare",
    unitPrice: 1.4,
    stripPrice: 14.0,
    unitsPerStrip: 10,
    stockQuantity: 180,
    dosage: "1 capsule 1-3 times daily",
    instructions: "Take with or without food. Titrate dose as prescribed.",
    precautions: "May cause drowsiness. Avoid alcohol and driving initially.",
    sideEffects: "Dizziness, drowsiness, fatigue, weight gain.",
  },
  {
    name: "Tamsulosin 0.4mg",
    genericName: "Tamsulosin",
    groupName: "Alpha Blockers",
    manufacturer: "UroHealth",
    unitPrice: 1.2,
    stripPrice: 12.0,
    unitsPerStrip: 10,
    stockQuantity: 200,
    dosage: "1 capsule daily, 30 minutes after the same meal",
    instructions: "Swallow whole. Do not crush or chew.",
    precautions: "May cause dizziness. Avoid sudden standing.",
    sideEffects: "Dizziness, headache, runny nose, ejaculation problems.",
  },
  {
    name: "Esomeprazole 40mg",
    genericName: "Esomeprazole",
    groupName: "Proton Pump Inhibitors",
    manufacturer: "GutCare",
    unitPrice: 1.0,
    stripPrice: 10.0,
    unitsPerStrip: 10,
    stockQuantity: 270,
    dosage: "1 capsule daily before a meal",
    instructions: "Swallow whole with water. Do not crush or chew.",
    precautions: "Long-term use may increase risk of kidney issues.",
    sideEffects: "Headache, diarrhea, nausea, abdominal pain.",
  },
  {
    name: "Loratadine 10mg",
    genericName: "Loratadine",
    groupName: "Antihistamines",
    manufacturer: "AllergyFree",
    unitPrice: 0.6,
    stripPrice: 6.0,
    unitsPerStrip: 10,
    stockQuantity: 420,
    dosage: "1 tablet daily",
    instructions: "Take with or without food. Less likely to cause drowsiness.",
    precautions: "Consult doctor if symptoms persist beyond 7 days.",
    sideEffects: "Headache, fatigue, dry mouth.",
  },
  {
    name: "Metoprolol 50mg",
    genericName: "Metoprolol",
    groupName: "Beta Blockers",
    manufacturer: "HeartCare",
    unitPrice: 0.8,
    stripPrice: 8.0,
    unitsPerStrip: 10,
    stockQuantity: 240,
    dosage: "1 tablet 1-2 times daily",
    instructions: "Take with or immediately after food.",
    precautions: "Monitor heart rate. Avoid abrupt discontinuation.",
    sideEffects: "Fatigue, dizziness, slow heart rate, diarrhea.",
  },
  {
    name: "Warfarin 5mg",
    genericName: "Warfarin",
    groupName: "Anticoagulants",
    manufacturer: "BloodSafe",
    unitPrice: 1.0,
    stripPrice: 10.0,
    unitsPerStrip: 10,
    stockQuantity: 160,
    dosage: "1 tablet daily, dose varies by INR",
    instructions: "Take at the same time each day. Monitor INR regularly.",
    precautions: "High bleeding risk. Avoid certain foods and drugs.",
    sideEffects: "Bleeding, bruising, nausea, hair loss.",
  },
  {
    name: "Pantoprazole 40mg",
    genericName: "Pantoprazole",
    groupName: "Proton Pump Inhibitors",
    manufacturer: "AcidRelief",
    unitPrice: 0.9,
    stripPrice: 9.0,
    unitsPerStrip: 10,
    stockQuantity: 290,
    dosage: "1 tablet daily before a meal",
    instructions: "Swallow whole. Do not crush or chew.",
    precautions: "Long-term use may affect magnesium levels.",
    sideEffects: "Headache, diarrhea, nausea, rash.",
  },
  {
    name: "Tramadol 50mg",
    genericName: "Tramadol",
    groupName: "Opioid Analgesics",
    manufacturer: "PainRelief",
    unitPrice: 1.5,
    stripPrice: 15.0,
    unitsPerStrip: 10,
    stockQuantity: 130,
    dosage: "1 tablet every 4-6 hours as needed",
    instructions: "Take with or without food. Do not exceed 400mg daily.",
    precautions: "Risk of dependence. Avoid alcohol and other CNS depressants.",
    sideEffects: "Dizziness, nausea, constipation, drowsiness.",
  },
  {
    name: "Rosuvastatin 10mg",
    genericName: "Rosuvastatin",
    groupName: "Statins",
    manufacturer: "LipidCare",
    unitPrice: 1.6,
    stripPrice: 16.0,
    unitsPerStrip: 10,
    stockQuantity: 190,
    dosage: "1 tablet daily, any time of day",
    instructions: "Take with or without food. Avoid grapefruit juice.",
    precautions: "Monitor liver function. Report muscle pain immediately.",
    sideEffects: "Muscle pain, headache, nausea, constipation.",
  },
  {
    name: "Cephalexin 500mg",
    genericName: "Cephalexin",
    groupName: "Cephalosporin Antibiotics",
    manufacturer: "BactiStop",
    unitPrice: 1.4,
    stripPrice: 14.0,
    unitsPerStrip: 10,
    stockQuantity: 200,
    dosage: "1 capsule 2-4 times daily",
    instructions: "Take with or without food. Complete full course.",
    precautions: "Inform doctor if allergic to penicillin.",
    sideEffects: "Diarrhea, nausea, rash, stomach upset.",
  },
  {
    name: "Budesonide 200mcg",
    genericName: "Budesonide",
    groupName: "Inhaled Corticosteroids",
    manufacturer: "BreatheEasy",
    unitPrice: 2.0,
    stripPrice: 20.0,
    unitsPerStrip: 10,
    stockQuantity: 110,
    dosage: "1-2 puffs twice daily via inhaler",
    instructions: "Rinse mouth after use to prevent thrush.",
    precautions: "Not for acute asthma attacks. Monitor for infections.",
    sideEffects: "Throat irritation, hoarseness, cough, oral thrush.",
  },
  {
    name: "Venlafaxine 75mg",
    genericName: "Venlafaxine",
    groupName: "SNRIs",
    manufacturer: "MoodCare",
    unitPrice: 1.3,
    stripPrice: 13.0,
    unitsPerStrip: 10,
    stockQuantity: 220,
    dosage: "1 capsule daily, with food",
    instructions: "Swallow whole. Do not crush or chew.",
    precautions: "Monitor blood pressure. Avoid abrupt discontinuation.",
    sideEffects: "Nausea, headache, insomnia, increased sweating.",
  },
  {
    name: "Allopurinol 100mg",
    genericName: "Allopurinol",
    groupName: "Antigout Agents",
    manufacturer: "GoutRelief",
    unitPrice: 0.7,
    stripPrice: 7.0,
    unitsPerStrip: 10,
    stockQuantity: 310,
    dosage: "1 tablet daily",
    instructions: "Take with food. Stay hydrated to prevent kidney stones.",
    precautions: "Monitor for skin rash. Avoid in acute gout attacks.",
    sideEffects: "Rash, nausea, diarrhea, drowsiness.",
  },
  {
    name: "Furosemide 40mg",
    genericName: "Furosemide",
    groupName: "Diuretics",
    manufacturer: "FluidCare",
    unitPrice: 0.6,
    stripPrice: 6.0,
    unitsPerStrip: 10,
    stockQuantity: 330,
    dosage: "1 tablet daily, usually in the morning",
    instructions: "Take with or without food. Monitor electrolyte levels.",
    precautions: "Avoid dehydration. Monitor kidney function.",
    sideEffects: "Dehydration, low potassium, dizziness, headache.",
  },
  {
    name: "Sitagliptin 100mg",
    genericName: "Sitagliptin",
    groupName: "Antidiabetics",
    manufacturer: "SugarControl",
    unitPrice: 2.2,
    stripPrice: 22.0,
    unitsPerStrip: 10,
    stockQuantity: 150,
    dosage: "1 tablet daily",
    instructions: "Take with or without food. Consistent timing recommended.",
    precautions: "Monitor kidney function. Not for type 1 diabetes.",
    sideEffects: "Headache, sore throat, nausea, diarrhea.",
  },
   {
    name: "Example 100mg",
    genericName: "Example",
    groupName: "Antidiabetics",
    manufacturer: "SugarControl",
    unitPrice: 2.2,
    stripPrice: 22.0,
    unitsPerStrip: 10,
    stockQuantity: 150,
    dosage: "1 tablet daily",
    instructions: "Take with or without food. Consistent timing recommended.",
    precautions: "Monitor kidney function. Not for type 1 diabetes.",
    sideEffects: "Headache, sore throat, nausea, diarrhea.",
  },
  {
    name: "Ayat",
    genericName: "Example",
    groupName: "Antidiabetics",
    manufacturer: "SugarControl",
    unitPrice: 2.2,
    stripPrice: 22.0,
    unitsPerStrip: 10,
    stockQuantity: 150,
    dosage: "1 tablet daily",
    instructions: "Take with or without food. Consistent timing recommended.",
    precautions: "Monitor kidney function. Not for type 1 diabetes.",
    sideEffects: "Headache, sore throat, nausea, diarrhea.",
  },
  {
    name: "Ayat 2",
    genericName: "Example",
    groupName: "Antidiabetics",
    manufacturer: "SugarControl",
    unitPrice: 2.2,
    stripPrice: 22.0,
    unitsPerStrip: 10,
    stockQuantity: 150,
    dosage: "1 tablet daily",
    instructions: "Take with or without food. Consistent timing recommended.",
    precautions: "Monitor kidney function. Not for type 1 diabetes.",
    sideEffects: "Headache, sore throat, nausea, diarrhea.",
  },
]

export default sampleMedicines